apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-site
  namespace: cv
spec:
  ingressClassName: nginx
  rules:
  - host: test.avakym-team.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cv-site
            port:
              number: 80