name: Deploy CV

on:
  push:
    branches:
      - main

jobs:
  build-pdf-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Копируем все нужные файлы в build 
      - name: Copy static files
        if: success()
        run: |
          mkdir -p build
          cp -r cv/* build/ 
      
      # Генерируем версию
      - name: Generate version
        id: version
        run: |
          SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="$(date +%Y.%m.%d)-${SHA_SHORT}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Заменяем плейсхолдер в HTML на версию
      - name: Replace version in HTML
        if: success()
        run: |
          sed -i 's/__VERSION__/${{ steps.version.outputs.VERSION }}/g' ./build/cv_now.html

       # Вставляем Id счетчика метрики
      - name: Replace version in HTML
        if: success()
        run: |
          sed -i 's/__METRIKA__/${{ secrets.METRIKA_ID }}/g' ./build/cv_now.html

      # Генерация PDF из HTML-файла
      - name: Convert HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        if: success()
        with:
          htmlFile: ./build/cv_now.html
          outputFile: ./build/resume_avvakumov.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "0mm", "left": "10mm", "right": "10mm", "bottom": "0mm"}, "scale": 0.95, "displayHeaderFooter": false, "pageRanges": "1"}'
      
      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.7
        if: success()
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          source: "./build/*"
          target: "/cv"
          debug: true
          strip_components: 1
